chore(deps): bump the all-cargo-version-updates group across 1 directory with 2 updates (#76)
Updates the requirements on [pyo3](https://github.com/pyo3/pyo3) and
[strum](https://github.com/Peternator7/strum) to permit the latest
version.
Updates `pyo3` to 0.28.2
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a
href="https://github.com/pyo3/pyo3/releases">pyo3's
releases</a>.</em></p>
<blockquote>
<h2>PyO3 0.28.2</h2>
<p>This patch release contains a soundness fix for subclassing native
types such as <code>PyList</code> with the <code>abi3</code> feature
enabled when targeting a minimum version of Python 3.12 or higher.
(Support for doing such subclassing was newly added in PyO3 0.28.0.)</p>
<p>PyO3 0.28.0 and 0.28.1 will be yanked.</p>
<p>This release also contains a correction to the FFI definition
<code>PyType_GetTypeDataSize</code> and incorrectly-generated
<code>__qualname__</code> on <code>#[pyclass]</code> enum variant types
when using <code>#[pyo3(name = &quot;...&quot;)]</code> option to rename
the enum and/or variant.</p>
<p>Thank you to the following contributors for the improvements:</p>
<p><a
href="https://github.com/davidhewitt"><code>@​davidhewitt</code></a>
<a href="https://github.com/Icxolu"><code>@​Icxolu</code></a>
<a href="https://github.com/ngoldbaum"><code>@​ngoldbaum</code></a></p>
</blockquote>
</details>
<details>
<summary>Changelog</summary>
<p><em>Sourced from <a
href="https://github.com/PyO3/pyo3/blob/main/CHANGELOG.md">pyo3's
changelog</a>.</em></p>
<blockquote>
<h2>[0.28.2] - 2026-02-18</h2>
<h3>Fixed</h3>
<ul>
<li>Fix complex enum <code>__qualname__</code> not using python name <a
href="https://redirect.github.com/PyO3/pyo3/pull/5815">#5815</a></li>
<li>Fix FFI definition <code>PyType_GetTypeDataSize</code> (was
incorrectly named <code>PyObject_GetTypeDataSize</code>). <a
href="https://redirect.github.com/PyO3/pyo3/pull/5819">#5819</a></li>
<li>Fix memory corruption when subclassing native types with
<code>abi3</code> feature on Python 3.12+ (newly enabled in PyO3
0.28.0). <a
href="https://redirect.github.com/PyO3/pyo3/pull/5823">#5823</a></li>
</ul>
<h2>[0.28.1] - 2026-02-14</h2>
<h3>Fixed</h3>
<ul>
<li>Fix <code>*args</code> / <code>**kwargs</code> support in<code>
experimental-async</code> feature (regressed in 0.28.0). <a
href="https://redirect.github.com/PyO3/pyo3/pull/5771">#5771</a></li>
<li>Fix <code>clippy::declare_interior_mutable_const</code> warning
inside <code>#[pyclass]</code> generated code on enums. <a
href="https://redirect.github.com/PyO3/pyo3/pull/5772">#5772</a></li>
<li>Fix <code>ambiguous_associated_items</code> compilation error when
deriving <code>FromPyObject</code> or using
<code>#[pyclass(from_py_object)]</code> macro on enums with
<code>Error</code> variant. <a
href="https://redirect.github.com/PyO3/pyo3/pull/5784">#5784</a></li>
<li>Fix <code>__qualname__</code> for complex <code>#[pyclass]</code>
enum variants to include the enum name. <a
href="https://redirect.github.com/PyO3/pyo3/pull/5796">#5796</a></li>
<li>Fix missing <code>std::sync::atomic::Ordering</code> import for
targets without atomic64. <a
href="https://redirect.github.com/PyO3/pyo3/pull/5808">#5808</a></li>
</ul>
<h2>[0.28.0] - 2026-02-01</h2>
<h3>Packaging</h3>
<ul>
<li>Bump MSRV to Rust 1.83. <a
href="https://redirect.github.com/PyO3/pyo3/pull/5531">#5531</a></li>
<li>Bump minimum supported <code>quote</code> version to 1.0.37. <a
href="https://redirect.github.com/PyO3/pyo3/pull/5531">#5531</a></li>
<li>Bump supported GraalPy version to 25.0. <a
href="https://redirect.github.com/PyO3/pyo3/pull/5542">#5542</a></li>
<li>Drop <code>memoffset</code> dependency. <a
href="https://redirect.github.com/PyO3/pyo3/pull/5545">#5545</a></li>
<li>Support for free-threaded Python is now opt-out rather than opt-in.
<a href="https://redirect.github.com/PyO3/pyo3/pull/5564">#5564</a></li>
<li>Bump <code>target-lexicon</code> dependency to 0.13.3. <a
href="https://redirect.github.com/PyO3/pyo3/pull/5571">#5571</a></li>
<li>Drop <code>indoc</code> and <code>unindent</code> dependencies. <a
href="https://redirect.github.com/PyO3/pyo3/pull/5608">#5608</a></li>
</ul>
<h3>Added</h3>
<ul>
<li>Add <code>__init__</code> support in <code>#[pymethods]</code>. <a
href="https://redirect.github.com/PyO3/pyo3/pull/4951">#4951</a></li>
<li>Expose <code>PySuper</code> on PyPy, GraalPy and ABI3 <a
href="https://redirect.github.com/PyO3/pyo3/pull/4951">#4951</a></li>
<li>Add <code>PyString::from_fmt</code> and <code>py_format!</code>
macro. <a
href="https://redirect.github.com/PyO3/pyo3/pull/5199">#5199</a></li>
<li>Add <code>#[pyclass(new = &quot;from_fields&quot;)]</code> option.
<a href="https://redirect.github.com/PyO3/pyo3/pull/5421">#5421</a></li>
<li>Add <code>pyo3::buffer::PyUntypedBuffer</code>, a type-erased form
of <code>PyBuffer&lt;T&gt;</code>. <a
href="https://redirect.github.com/PyO3/pyo3/pull/5458">#5458</a></li>
<li>Add <code>PyBytes::new_with_writer</code> <a
href="https://redirect.github.com/PyO3/pyo3/pull/5517">#5517</a></li>
<li>Add <code>PyClass::NAME</code>. <a
href="https://redirect.github.com/PyO3/pyo3/pull/5579">#5579</a></li>
<li>Add <code>pyo3_build_config::add_libpython_rpath_link_args</code>.
<a href="https://redirect.github.com/PyO3/pyo3/pull/5624">#5624</a></li>
<li>Add <code>PyBackedStr::clone_ref</code> and
<code>PyBackedBytes::clone_ref</code> methods. <a
href="https://redirect.github.com/PyO3/pyo3/pull/5654">#5654</a></li>
<li>Add <code>PyCapsule::new_with_pointer</code> and
<code>PyCapsule::new_with_pointer_and_destructor</code> for creating
capsules with raw pointers. <a
href="https://redirect.github.com/PyO3/pyo3/pull/5689">#5689</a></li>
<li>Add <code>#[deleter]</code> attribute to implement property deleters
in <code>#[methods]</code>. <a
href="https://redirect.github.com/PyO3/pyo3/pull/5699">#5699</a></li>
<li>Add <code>IntoPyObject</code> and <code>FromPyObject</code>
implementations for <code>uuid::NonNilUuid</code>. <a
href="https://redirect.github.com/PyO3/pyo3/pull/5707">#5707</a></li>
<li>Add <code>PyBackedStr::as_str</code> and
<code>PyBackedStr::as_py_str</code> methods. <a
href="https://redirect.github.com/PyO3/pyo3/pull/5723">#5723</a></li>
<li>Add support for subclassing native types (<code>PyDict</code>,
exceptions, ...) when building for abi3 on Python 3.12+. <a
href="https://redirect.github.com/PyO3/pyo3/pull/5733">#5733</a></li>
<li>Add support for subclassing <code>PyList</code> when building for
Python 3.12+. <a
href="https://redirect.github.com/PyO3/pyo3/pull/5734">#5734</a></li>
<li>FFI definitions:
<ul>
<li>Add FFI definitions <code>PyEval_GetFrameBuiltins</code>,
<code>PyEval_GetFrameGlobals</code> and
<code>PyEval_GetFrameLocals</code> on Python 3.13 and up. <a
href="https://redirect.github.com/PyO3/pyo3/pull/5590">#5590</a></li>
<li>Add FFI definitions <code>PyObject_New</code>,
<code>PyObject_NewVar</code>, <code>PyObject_GC_Resize</code>,
<code>PyObject_GC_New</code>, and <code>PyObject_GC_NewVar</code>. <a
href="https://redirect.github.com/PyO3/pyo3/pull/5591">#5591</a></li>
</ul>
</li>
</ul>
<!-- raw HTML omitted -->
</blockquote>
<p>... (truncated)</p>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/PyO3/pyo3/commit/2b392c8500673520066486f6098cbf2316211ff6"><code>2b392c8</code></a>
release: 0.28.2</li>
<li><a
href="https://github.com/PyO3/pyo3/commit/7e44c1d64d40a12e0bd55c819e3feda5322fc219"><code>7e44c1d</code></a>
fix complex enum <code>__qualname__</code> not using python name (<a
href="https://redirect.github.com/pyo3/pyo3/issues/5815">#5815</a>)</li>
<li><a
href="https://github.com/PyO3/pyo3/commit/75abd8602896b350fd8c778e52e0a74b4644ccca"><code>75abd86</code></a>
fix memory corruption when subclassing variable-size types (e.g.
<code>abi3</code> + 3.1...</li>
<li><a
href="https://github.com/PyO3/pyo3/commit/b62c7a278fc14e9afb0d73ab1ded7ba00cda3be2"><code>b62c7a2</code></a>
Fix typo in PyType_GetTypeDataSize bindings (<a
href="https://redirect.github.com/pyo3/pyo3/issues/5819">#5819</a>)</li>
<li><a
href="https://github.com/PyO3/pyo3/commit/45f49ff9f50538c5bc2ea2c5045ee58f7270bfad"><code>45f49ff</code></a>
release: 0.28.1</li>
<li><a
href="https://github.com/PyO3/pyo3/commit/56c34d630b8c133b3298ccae601dff2f6d5a9798"><code>56c34d6</code></a>
Document Py_GIL_DISABLED in pyo3-build-config docs (<a
href="https://redirect.github.com/pyo3/pyo3/issues/5810">#5810</a>)</li>
<li><a
href="https://github.com/PyO3/pyo3/commit/92bc9efd51f70d72d71223b2d661b7d9cc074ef6"><code>92bc9ef</code></a>
Avoid unused variable warning with a debug Python build (<a
href="https://redirect.github.com/pyo3/pyo3/issues/5811">#5811</a>)</li>
<li><a
href="https://github.com/PyO3/pyo3/commit/ca5df1a72d745c27327cddd3726aebda88556614"><code>ca5df1a</code></a>
ci: re-enable <code>list_get_item_unchecked</code> benchmark on
free-threaded build (<a
href="https://redirect.github.com/pyo3/pyo3/issues/5812">#5812</a>)</li>
<li><a
href="https://github.com/PyO3/pyo3/commit/413d9b5b0130dd636d250be03d807b6091beab5e"><code>413d9b5</code></a>
Fix missing <code>std::sync::atomic::Ordering</code> import for targets
without atomic64...</li>
<li><a
href="https://github.com/PyO3/pyo3/commit/1c764cdc377d41f7117524fd9ecb311a81a2029c"><code>1c764cd</code></a>
docs: improve messaging around <code>#[pyclass(from_py_object)]</code>
change (<a
href="https://redirect.github.com/pyo3/pyo3/issues/5798">#5798</a>)</li>
<li>Additional commits viewable in <a
href="https://github.com/pyo3/pyo3/compare/v0.27.2...v0.28.2">compare
view</a></li>
</ul>
</details>
<br />

Updates `strum` to 0.28.0
<details>
<summary>Changelog</summary>
<p><em>Sourced from <a
href="https://github.com/Peternator7/strum/blob/master/CHANGELOG.md">strum's
changelog</a>.</em></p>
<blockquote>
<h2>0.28.0</h2>
<ul>
<li>
<p><a
href="https://redirect.github.com/Peternator7/strum/pull/461">#461</a>:
Allow any kind of passthrough attributes on
<code>EnumDiscriminants</code>.</p>
<ul>
<li>Previously only list-style attributes (e.g.
<code>#[strum_discriminants(derive(...))]</code>) were supported. Now
path-only
(e.g. <code>#[strum_discriminants(non_exhaustive)]</code>) and
name/value (e.g. <code>#[strum_discriminants(doc =
&quot;foo&quot;)]</code>)
attributes are also supported.</li>
</ul>
</li>
<li>
<p><a
href="https://redirect.github.com/Peternator7/strum/pull/462">#462</a>:
Add missing <code>#[automatically_derived]</code> to generated impls not
covered by <a
href="https://redirect.github.com/Peternator7/strum/pull/444">#444</a>.</p>
</li>
<li>
<p><a
href="https://redirect.github.com/Peternator7/strum/pull/466">#466</a>:
Bump MSRV to 1.71, required to keep up with updated <code>syn</code> and
<code>windows-sys</code> dependencies. This is a breaking change if
you're on an old version of rust.</p>
</li>
<li>
<p><a
href="https://redirect.github.com/Peternator7/strum/pull/469">#469</a>:
Use absolute paths in generated proc macro code to avoid
potential name conflicts.</p>
</li>
<li>
<p><a
href="https://redirect.github.com/Peternator7/strum/pull/465">#465</a>:
Upgrade <code>phf</code> dependency to v0.13.</p>
</li>
<li>
<p><a
href="https://redirect.github.com/Peternator7/strum/pull/473">#473</a>:
Fix <code>cargo fmt</code> / <code>clippy</code> issues and add GitHub
Actions CI.</p>
</li>
<li>
<p><a
href="https://redirect.github.com/Peternator7/strum/pull/477">#477</a>:
<code>strum::ParseError</code> now implements
<code>core::fmt::Display</code> instead
<code>std::fmt::Display</code> to make it <code>#[no_std]</code>
compatible. Note the <code>Error</code> trait wasn't available in core
until <code>1.81</code>
so <code>strum::ParseError</code> still only implements that in std.</p>
</li>
<li>
<p><a
href="https://redirect.github.com/Peternator7/strum/pull/476">#476</a>:
<strong>Breaking Change</strong> - <code>EnumString</code> now
implements <code>From&lt;&amp;str&gt;</code>
(infallible) instead of <code>TryFrom&lt;&amp;str&gt;</code> when the
enum has a <code>#[strum(default)]</code> variant. This more accurately
reflects that parsing cannot fail in that case. If you need the old
<code>TryFrom</code> behavior, you can opt back in using
<code>parse_error_ty</code> and <code>parse_error_fn</code>:</p>
<pre lang="rust"><code>#[derive(EnumString)]
#[strum(parse_error_ty = strum::ParseError, parse_error_fn =
make_error)]
pub enum Color {
    Red,
    #[strum(default)]
    Other(String),
}
<p>fn make_error(x: &amp;str) -&gt; strum::ParseError {
strum::ParseError::VariantNotFound
}
</code></pre></p>
</li>
<li>
<p><a
href="https://redirect.github.com/Peternator7/strum/pull/431">#431</a>:
Fix bug where <code>EnumString</code> ignored the
<code>parse_err_ty</code>
attribute when the enum had a <code>#[strum(default)]</code>
variant.</p>
</li>
<li>
<p><a
href="https://redirect.github.com/Peternator7/strum/pull/474">#474</a>:
EnumDiscriminants will now copy <code>default</code> over from the
original enum to the Discriminant enum.</p>
<pre lang="rust"><code>#[derive(Debug, Default, EnumDiscriminants)]
#[strum_discriminants(derive(Default))] // &lt;- Remove this in 0.28.
enum MyEnum {
    #[default] // &lt;- Will be the #[default] on the MyEnumDiscriminant
    #[strum_discriminants(default)] // &lt;- Remove this in 0.28
    Variant0,
    Variant1 { a: NonDefault },
}
</code></pre>
</li>
</ul>
<!-- raw HTML omitted -->
</blockquote>
<p>... (truncated)</p>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/Peternator7/strum/commit/7376771128834d28bb9beba5c39846cba62e71ec"><code>7376771</code></a>
Peternator7/0.28 (<a
href="https://redirect.github.com/Peternator7/strum/issues/475">#475</a>)</li>
<li><a
href="https://github.com/Peternator7/strum/commit/26e63cd964a2e364331a5dd977d589bb9f649d8c"><code>26e63cd</code></a>
Display exists in core (<a
href="https://redirect.github.com/Peternator7/strum/issues/477">#477</a>)</li>
<li><a
href="https://github.com/Peternator7/strum/commit/9334c728eedaa8a992d1388a8f4564bbccad1934"><code>9334c72</code></a>
Make TryFrom and FromStr infallible if there's a default (<a
href="https://redirect.github.com/Peternator7/strum/issues/476">#476</a>)</li>
<li><a
href="https://github.com/Peternator7/strum/commit/0ccbbf823c16e827afc263182cd55e99e3b2a52e"><code>0ccbbf8</code></a>
Honor parse_err_ty attribute when the enum has a default variant (<a
href="https://redirect.github.com/Peternator7/strum/issues/431">#431</a>)</li>
<li><a
href="https://github.com/Peternator7/strum/commit/2c9e5a9259189ce8397f2f4967060240c6bafd74"><code>2c9e5a9</code></a>
Automatically add Default implementation to EnumDiscriminant if it
exists on ...</li>
<li><a
href="https://github.com/Peternator7/strum/commit/e241243e48359b8b811b8eaccdcfa1ae87138e0d"><code>e241243</code></a>
Fix existing cargo fmt + clippy issues and add GH actions (<a
href="https://redirect.github.com/Peternator7/strum/issues/473">#473</a>)</li>
<li><a
href="https://github.com/Peternator7/strum/commit/639b67fefd20eaead1c5d2ea794e9afe70a00312"><code>639b67f</code></a>
feat: allow any kind of passthrough attributes on
<code>EnumDiscriminants</code> (<a
href="https://redirect.github.com/Peternator7/strum/issues/461">#461</a>)</li>
<li><a
href="https://github.com/Peternator7/strum/commit/0ea1e2d0fd1460e7492ea32e6b460394d9199ff8"><code>0ea1e2d</code></a>
docs: Fix typo (<a
href="https://redirect.github.com/Peternator7/strum/issues/463">#463</a>)</li>
<li><a
href="https://github.com/Peternator7/strum/commit/36c051b91086b37d531c63ccf5a49266832a846d"><code>36c051b</code></a>
Upgrade <code>phf</code> to v0.13 (<a
href="https://redirect.github.com/Peternator7/strum/issues/465">#465</a>)</li>
<li><a
href="https://github.com/Peternator7/strum/commit/9328b38617dc6f4a3bc5fdac03883d3fc766cf34"><code>9328b38</code></a>
Use absolute paths in proc macro (<a
href="https://redirect.github.com/Peternator7/strum/issues/469">#469</a>)</li>
<li>Additional commits viewable in <a
href="https://github.com/Peternator7/strum/compare/v0.27.0...v0.28.0">compare
view</a></li>
</ul>
</details>
<br />


Dependabot will resolve any conflicts with this PR as long as you don't
alter it yourself. You can also trigger a rebase manually by commenting
`@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits
that have been made to it
- `@dependabot show <dependency name> ignore conditions` will show all
of the ignore conditions of the specified dependency
- `@dependabot ignore <dependency name> major version` will close this
group update PR and stop Dependabot creating any more for the specific
dependency's major version (unless you unignore this specific
dependency's major version or upgrade to it yourself)
- `@dependabot ignore <dependency name> minor version` will close this
group update PR and stop Dependabot creating any more for the specific
dependency's minor version (unless you unignore this specific
dependency's minor version or upgrade to it yourself)
- `@dependabot ignore <dependency name>` will close this group update PR
and stop Dependabot creating any more for the specific dependency
(unless you unignore this specific dependency or upgrade to it yourself)
- `@dependabot unignore <dependency name>` will remove all of the ignore
conditions of the specified dependency
- `@dependabot unignore <dependency name> <ignore condition>` will
remove the ignore condition of the specified dependency and ignore
conditions


</details>

---------

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
Co-authored-by: Copilot <198982749+Copilot@users.noreply.github.com>
Co-authored-by: nyurik <1641515+nyurik@users.noreply.github.com>
Co-authored-by: Yuri Astrakhan <yuriastrakhan@gmail.com>